/*
 * generated by Xtext 2.25.0
 */
package fr.ensma.dsl.ui.tests;

import com.google.inject.Injector;
import fr.ensma.dsl.tac.ui.internal.TacActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class ThreeAddressCodeUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return TacActivator.getInstance().getInjector("fr.ensma.dsl.ThreeAddressCode");
	}

}
