/*
 * generated by Xtext 2.25.0
 */
package fr.ensma.dsl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractThreeAddressCodeScopeProvider extends DelegatingScopeProvider {
}
