/*
 * generated by Xtext 2.25.0
 */
package fr.ensma.dsl.parser.antlr;

import com.google.inject.Inject;
import fr.ensma.dsl.parser.antlr.internal.InternalThreeAddressCodeParser;
import fr.ensma.dsl.services.ThreeAddressCodeGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class ThreeAddressCodeParser extends AbstractAntlrParser {

	@Inject
	private ThreeAddressCodeGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalThreeAddressCodeParser createParser(XtextTokenStream stream) {
		return new InternalThreeAddressCodeParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "TAC";
	}

	public ThreeAddressCodeGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(ThreeAddressCodeGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
