/*
 * generated by Xtext 2.25.0
 */
package fr.ensma.dsl.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class ThreeAddressCodeAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("fr/ensma/dsl/parser/antlr/internal/InternalThreeAddressCode.tokens");
	}
}
