/*
 * generated by Xtext 2.25.0
 */
package fr.ensma.dsl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import fr.ensma.dsl.ThreeAddressCodeRuntimeModule;
import fr.ensma.dsl.ThreeAddressCodeStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class ThreeAddressCodeIdeSetup extends ThreeAddressCodeStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new ThreeAddressCodeRuntimeModule(), new ThreeAddressCodeIdeModule()));
	}
	
}
