/*
 * generated by Xtext 2.25.0
 */
package fr.ensma.dsl.ide;


/**
 * Use this class to register ide components.
 */
public class ThreeAddressCodeIdeModule extends AbstractThreeAddressCodeIdeModule {
}
