/*
 * generated by Xtext 2.25.0
 */
package fr.ensma.dsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class ThreeAddressCodeUiModule extends AbstractThreeAddressCodeUiModule {

	public ThreeAddressCodeUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
