/**
 * generated by Xtext 2.25.0
 */
package fr.ensma.dsl.threeAddressCode;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Assign Operation</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.ensma.dsl.threeAddressCode.AssignOperation#getFunctionCall <em>Function Call</em>}</li>
 * </ul>
 *
 * @see fr.ensma.dsl.threeAddressCode.ThreeAddressCodePackage#getAssignOperation()
 * @model
 * @generated
 */
public interface AssignOperation extends EObject
{
  /**
   * Returns the value of the '<em><b>Function Call</b></em>' containment reference list.
   * The list contents are of type {@link fr.ensma.dsl.threeAddressCode.FunctionCall}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Function Call</em>' containment reference list.
   * @see fr.ensma.dsl.threeAddressCode.ThreeAddressCodePackage#getAssignOperation_FunctionCall()
   * @model containment="true"
   * @generated
   */
  EList<FunctionCall> getFunctionCall();

} // AssignOperation
