/**
 * generated by Xtext 2.25.0
 */
package fr.ensma.dsl.threeAddressCode;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Boulean Exrpession</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see fr.ensma.dsl.threeAddressCode.ThreeAddressCodePackage#getBouleanExrpession()
 * @model
 * @generated
 */
public interface BouleanExrpession extends If
{
} // BouleanExrpession
