/**
 * generated by Xtext 2.25.0
 */
package fr.ensma.dsl.threeAddressCode;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Function Param</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.ensma.dsl.threeAddressCode.FunctionParam#getStruct <em>Struct</em>}</li>
 *   <li>{@link fr.ensma.dsl.threeAddressCode.FunctionParam#getDatatype <em>Datatype</em>}</li>
 *   <li>{@link fr.ensma.dsl.threeAddressCode.FunctionParam#getName <em>Name</em>}</li>
 * </ul>
 *
 * @see fr.ensma.dsl.threeAddressCode.ThreeAddressCodePackage#getFunctionParam()
 * @model
 * @generated
 */
public interface FunctionParam extends EObject
{
  /**
   * Returns the value of the '<em><b>Struct</b></em>' containment reference list.
   * The list contents are of type {@link fr.ensma.dsl.threeAddressCode.Struct}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Struct</em>' containment reference list.
   * @see fr.ensma.dsl.threeAddressCode.ThreeAddressCodePackage#getFunctionParam_Struct()
   * @model containment="true"
   * @generated
   */
  EList<Struct> getStruct();

  /**
   * Returns the value of the '<em><b>Datatype</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Datatype</em>' containment reference.
   * @see #setDatatype(DataType)
   * @see fr.ensma.dsl.threeAddressCode.ThreeAddressCodePackage#getFunctionParam_Datatype()
   * @model containment="true"
   * @generated
   */
  DataType getDatatype();

  /**
   * Sets the value of the '{@link fr.ensma.dsl.threeAddressCode.FunctionParam#getDatatype <em>Datatype</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Datatype</em>' containment reference.
   * @see #getDatatype()
   * @generated
   */
  void setDatatype(DataType value);

  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see fr.ensma.dsl.threeAddressCode.ThreeAddressCodePackage#getFunctionParam_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link fr.ensma.dsl.threeAddressCode.FunctionParam#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

} // FunctionParam
