/**
 * generated by Xtext 2.25.0
 */
package fr.ensma.dsl.threeAddressCode;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Function Call</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.ensma.dsl.threeAddressCode.FunctionCall#getFunctionCall <em>Function Call</em>}</li>
 *   <li>{@link fr.ensma.dsl.threeAddressCode.FunctionCall#getFunctionArgument <em>Function Argument</em>}</li>
 * </ul>
 *
 * @see fr.ensma.dsl.threeAddressCode.ThreeAddressCodePackage#getFunctionCall()
 * @model
 * @generated
 */
public interface FunctionCall extends EObject
{
  /**
   * Returns the value of the '<em><b>Function Call</b></em>' reference list.
   * The list contents are of type {@link fr.ensma.dsl.threeAddressCode.Function}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Function Call</em>' reference list.
   * @see fr.ensma.dsl.threeAddressCode.ThreeAddressCodePackage#getFunctionCall_FunctionCall()
   * @model
   * @generated
   */
  EList<Function> getFunctionCall();

  /**
   * Returns the value of the '<em><b>Function Argument</b></em>' containment reference list.
   * The list contents are of type {@link fr.ensma.dsl.threeAddressCode.FunctionArgument}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Function Argument</em>' containment reference list.
   * @see fr.ensma.dsl.threeAddressCode.ThreeAddressCodePackage#getFunctionCall_FunctionArgument()
   * @model containment="true"
   * @generated
   */
  EList<FunctionArgument> getFunctionArgument();

} // FunctionCall
