/**
 * generated by Xtext 2.25.0
 */
package fr.ensma.dsl.threeAddressCode;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Struct</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see fr.ensma.dsl.threeAddressCode.ThreeAddressCodePackage#getStruct()
 * @model
 * @generated
 */
public interface Struct extends EObject
{
} // Struct
