/**
 * generated by Xtext 2.25.0
 */
package fr.ensma.dsl.threeAddressCode;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>TAC</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.ensma.dsl.threeAddressCode.TAC#getTac <em>Tac</em>}</li>
 * </ul>
 *
 * @see fr.ensma.dsl.threeAddressCode.ThreeAddressCodePackage#getTAC()
 * @model
 * @generated
 */
public interface TAC extends EObject
{
  /**
   * Returns the value of the '<em><b>Tac</b></em>' containment reference list.
   * The list contents are of type {@link fr.ensma.dsl.threeAddressCode.FunctionDef}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Tac</em>' containment reference list.
   * @see fr.ensma.dsl.threeAddressCode.ThreeAddressCodePackage#getTAC_Tac()
   * @model containment="true"
   * @generated
   */
  EList<FunctionDef> getTac();

} // TAC
