/**
 * generated by Xtext 2.25.0
 */
package fr.ensma.dsl.threeAddressCode;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see fr.ensma.dsl.threeAddressCode.ThreeAddressCodeFactory
 * @model kind="package"
 * @generated
 */
public interface ThreeAddressCodePackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "threeAddressCode";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.ensma.fr/dsl/ThreeAddressCode";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "threeAddressCode";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  ThreeAddressCodePackage eINSTANCE = fr.ensma.dsl.threeAddressCode.impl.ThreeAddressCodePackageImpl.init();

  /**
   * The meta object id for the '{@link fr.ensma.dsl.threeAddressCode.impl.TACImpl <em>TAC</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.ensma.dsl.threeAddressCode.impl.TACImpl
   * @see fr.ensma.dsl.threeAddressCode.impl.ThreeAddressCodePackageImpl#getTAC()
   * @generated
   */
  int TAC = 0;

  /**
   * The feature id for the '<em><b>Tac</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TAC__TAC = 0;

  /**
   * The number of structural features of the '<em>TAC</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TAC_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link fr.ensma.dsl.threeAddressCode.impl.FunctionDefImpl <em>Function Def</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.ensma.dsl.threeAddressCode.impl.FunctionDefImpl
   * @see fr.ensma.dsl.threeAddressCode.impl.ThreeAddressCodePackageImpl#getFunctionDef()
   * @generated
   */
  int FUNCTION_DEF = 1;

  /**
   * The feature id for the '<em><b>Function</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTION_DEF__FUNCTION = 0;

  /**
   * The feature id for the '<em><b>Functionparam</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTION_DEF__FUNCTIONPARAM = 1;

  /**
   * The feature id for the '<em><b>Struct</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTION_DEF__STRUCT = 2;

  /**
   * The feature id for the '<em><b>Label</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTION_DEF__LABEL = 3;

  /**
   * The feature id for the '<em><b>Goto</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTION_DEF__GOTO = 4;

  /**
   * The feature id for the '<em><b>If</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTION_DEF__IF = 5;

  /**
   * The feature id for the '<em><b>Function Call</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTION_DEF__FUNCTION_CALL = 6;

  /**
   * The feature id for the '<em><b>Assign Op</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTION_DEF__ASSIGN_OP = 7;

  /**
   * The number of structural features of the '<em>Function Def</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTION_DEF_FEATURE_COUNT = 8;

  /**
   * The meta object id for the '{@link fr.ensma.dsl.threeAddressCode.impl.FunctionCallImpl <em>Function Call</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.ensma.dsl.threeAddressCode.impl.FunctionCallImpl
   * @see fr.ensma.dsl.threeAddressCode.impl.ThreeAddressCodePackageImpl#getFunctionCall()
   * @generated
   */
  int FUNCTION_CALL = 2;

  /**
   * The feature id for the '<em><b>Function Call</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTION_CALL__FUNCTION_CALL = 0;

  /**
   * The feature id for the '<em><b>Function Argument</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTION_CALL__FUNCTION_ARGUMENT = 1;

  /**
   * The number of structural features of the '<em>Function Call</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTION_CALL_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link fr.ensma.dsl.threeAddressCode.impl.FunctionParamImpl <em>Function Param</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.ensma.dsl.threeAddressCode.impl.FunctionParamImpl
   * @see fr.ensma.dsl.threeAddressCode.impl.ThreeAddressCodePackageImpl#getFunctionParam()
   * @generated
   */
  int FUNCTION_PARAM = 3;

  /**
   * The feature id for the '<em><b>Struct</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTION_PARAM__STRUCT = 0;

  /**
   * The feature id for the '<em><b>Datatype</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTION_PARAM__DATATYPE = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTION_PARAM__NAME = 2;

  /**
   * The number of structural features of the '<em>Function Param</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTION_PARAM_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link fr.ensma.dsl.threeAddressCode.impl.FunctionArgumentImpl <em>Function Argument</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.ensma.dsl.threeAddressCode.impl.FunctionArgumentImpl
   * @see fr.ensma.dsl.threeAddressCode.impl.ThreeAddressCodePackageImpl#getFunctionArgument()
   * @generated
   */
  int FUNCTION_ARGUMENT = 4;

  /**
   * The number of structural features of the '<em>Function Argument</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTION_ARGUMENT_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link fr.ensma.dsl.threeAddressCode.impl.DataTypeImpl <em>Data Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.ensma.dsl.threeAddressCode.impl.DataTypeImpl
   * @see fr.ensma.dsl.threeAddressCode.impl.ThreeAddressCodePackageImpl#getDataType()
   * @generated
   */
  int DATA_TYPE = 5;

  /**
   * The number of structural features of the '<em>Data Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATA_TYPE_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link fr.ensma.dsl.threeAddressCode.impl.StructImpl <em>Struct</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.ensma.dsl.threeAddressCode.impl.StructImpl
   * @see fr.ensma.dsl.threeAddressCode.impl.ThreeAddressCodePackageImpl#getStruct()
   * @generated
   */
  int STRUCT = 6;

  /**
   * The number of structural features of the '<em>Struct</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRUCT_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link fr.ensma.dsl.threeAddressCode.impl.GotoImpl <em>Goto</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.ensma.dsl.threeAddressCode.impl.GotoImpl
   * @see fr.ensma.dsl.threeAddressCode.impl.ThreeAddressCodePackageImpl#getGoto()
   * @generated
   */
  int GOTO = 7;

  /**
   * The number of structural features of the '<em>Goto</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GOTO_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link fr.ensma.dsl.threeAddressCode.impl.LabelImpl <em>Label</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.ensma.dsl.threeAddressCode.impl.LabelImpl
   * @see fr.ensma.dsl.threeAddressCode.impl.ThreeAddressCodePackageImpl#getLabel()
   * @generated
   */
  int LABEL = 8;

  /**
   * The number of structural features of the '<em>Label</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LABEL_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link fr.ensma.dsl.threeAddressCode.impl.IfImpl <em>If</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.ensma.dsl.threeAddressCode.impl.IfImpl
   * @see fr.ensma.dsl.threeAddressCode.impl.ThreeAddressCodePackageImpl#getIf()
   * @generated
   */
  int IF = 9;

  /**
   * The number of structural features of the '<em>If</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IF_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link fr.ensma.dsl.threeAddressCode.impl.AssignOperationImpl <em>Assign Operation</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.ensma.dsl.threeAddressCode.impl.AssignOperationImpl
   * @see fr.ensma.dsl.threeAddressCode.impl.ThreeAddressCodePackageImpl#getAssignOperation()
   * @generated
   */
  int ASSIGN_OPERATION = 10;

  /**
   * The feature id for the '<em><b>Function Call</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASSIGN_OPERATION__FUNCTION_CALL = 0;

  /**
   * The number of structural features of the '<em>Assign Operation</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASSIGN_OPERATION_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link fr.ensma.dsl.threeAddressCode.impl.FunctionImpl <em>Function</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.ensma.dsl.threeAddressCode.impl.FunctionImpl
   * @see fr.ensma.dsl.threeAddressCode.impl.ThreeAddressCodePackageImpl#getFunction()
   * @generated
   */
  int FUNCTION = 11;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTION__NAME = 0;

  /**
   * The number of structural features of the '<em>Function</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTION_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link fr.ensma.dsl.threeAddressCode.impl.BouleanExrpessionImpl <em>Boulean Exrpession</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.ensma.dsl.threeAddressCode.impl.BouleanExrpessionImpl
   * @see fr.ensma.dsl.threeAddressCode.impl.ThreeAddressCodePackageImpl#getBouleanExrpession()
   * @generated
   */
  int BOULEAN_EXRPESSION = 12;

  /**
   * The number of structural features of the '<em>Boulean Exrpession</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOULEAN_EXRPESSION_FEATURE_COUNT = IF_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link fr.ensma.dsl.threeAddressCode.impl.ArithmeticOperationImpl <em>Arithmetic Operation</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.ensma.dsl.threeAddressCode.impl.ArithmeticOperationImpl
   * @see fr.ensma.dsl.threeAddressCode.impl.ThreeAddressCodePackageImpl#getArithmeticOperation()
   * @generated
   */
  int ARITHMETIC_OPERATION = 13;

  /**
   * The number of structural features of the '<em>Arithmetic Operation</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARITHMETIC_OPERATION_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link fr.ensma.dsl.threeAddressCode.impl.LogicalOperationImpl <em>Logical Operation</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.ensma.dsl.threeAddressCode.impl.LogicalOperationImpl
   * @see fr.ensma.dsl.threeAddressCode.impl.ThreeAddressCodePackageImpl#getLogicalOperation()
   * @generated
   */
  int LOGICAL_OPERATION = 14;

  /**
   * The number of structural features of the '<em>Logical Operation</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOGICAL_OPERATION_FEATURE_COUNT = BOULEAN_EXRPESSION_FEATURE_COUNT + 0;


  /**
   * Returns the meta object for class '{@link fr.ensma.dsl.threeAddressCode.TAC <em>TAC</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>TAC</em>'.
   * @see fr.ensma.dsl.threeAddressCode.TAC
   * @generated
   */
  EClass getTAC();

  /**
   * Returns the meta object for the containment reference list '{@link fr.ensma.dsl.threeAddressCode.TAC#getTac <em>Tac</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Tac</em>'.
   * @see fr.ensma.dsl.threeAddressCode.TAC#getTac()
   * @see #getTAC()
   * @generated
   */
  EReference getTAC_Tac();

  /**
   * Returns the meta object for class '{@link fr.ensma.dsl.threeAddressCode.FunctionDef <em>Function Def</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Function Def</em>'.
   * @see fr.ensma.dsl.threeAddressCode.FunctionDef
   * @generated
   */
  EClass getFunctionDef();

  /**
   * Returns the meta object for the containment reference list '{@link fr.ensma.dsl.threeAddressCode.FunctionDef#getFunction <em>Function</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Function</em>'.
   * @see fr.ensma.dsl.threeAddressCode.FunctionDef#getFunction()
   * @see #getFunctionDef()
   * @generated
   */
  EReference getFunctionDef_Function();

  /**
   * Returns the meta object for the containment reference list '{@link fr.ensma.dsl.threeAddressCode.FunctionDef#getFunctionparam <em>Functionparam</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Functionparam</em>'.
   * @see fr.ensma.dsl.threeAddressCode.FunctionDef#getFunctionparam()
   * @see #getFunctionDef()
   * @generated
   */
  EReference getFunctionDef_Functionparam();

  /**
   * Returns the meta object for the containment reference list '{@link fr.ensma.dsl.threeAddressCode.FunctionDef#getStruct <em>Struct</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Struct</em>'.
   * @see fr.ensma.dsl.threeAddressCode.FunctionDef#getStruct()
   * @see #getFunctionDef()
   * @generated
   */
  EReference getFunctionDef_Struct();

  /**
   * Returns the meta object for the containment reference list '{@link fr.ensma.dsl.threeAddressCode.FunctionDef#getLabel <em>Label</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Label</em>'.
   * @see fr.ensma.dsl.threeAddressCode.FunctionDef#getLabel()
   * @see #getFunctionDef()
   * @generated
   */
  EReference getFunctionDef_Label();

  /**
   * Returns the meta object for the containment reference list '{@link fr.ensma.dsl.threeAddressCode.FunctionDef#getGoto <em>Goto</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Goto</em>'.
   * @see fr.ensma.dsl.threeAddressCode.FunctionDef#getGoto()
   * @see #getFunctionDef()
   * @generated
   */
  EReference getFunctionDef_Goto();

  /**
   * Returns the meta object for the containment reference list '{@link fr.ensma.dsl.threeAddressCode.FunctionDef#getIf <em>If</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>If</em>'.
   * @see fr.ensma.dsl.threeAddressCode.FunctionDef#getIf()
   * @see #getFunctionDef()
   * @generated
   */
  EReference getFunctionDef_If();

  /**
   * Returns the meta object for the containment reference list '{@link fr.ensma.dsl.threeAddressCode.FunctionDef#getFunctionCall <em>Function Call</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Function Call</em>'.
   * @see fr.ensma.dsl.threeAddressCode.FunctionDef#getFunctionCall()
   * @see #getFunctionDef()
   * @generated
   */
  EReference getFunctionDef_FunctionCall();

  /**
   * Returns the meta object for the containment reference list '{@link fr.ensma.dsl.threeAddressCode.FunctionDef#getAssignOp <em>Assign Op</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Assign Op</em>'.
   * @see fr.ensma.dsl.threeAddressCode.FunctionDef#getAssignOp()
   * @see #getFunctionDef()
   * @generated
   */
  EReference getFunctionDef_AssignOp();

  /**
   * Returns the meta object for class '{@link fr.ensma.dsl.threeAddressCode.FunctionCall <em>Function Call</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Function Call</em>'.
   * @see fr.ensma.dsl.threeAddressCode.FunctionCall
   * @generated
   */
  EClass getFunctionCall();

  /**
   * Returns the meta object for the reference list '{@link fr.ensma.dsl.threeAddressCode.FunctionCall#getFunctionCall <em>Function Call</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Function Call</em>'.
   * @see fr.ensma.dsl.threeAddressCode.FunctionCall#getFunctionCall()
   * @see #getFunctionCall()
   * @generated
   */
  EReference getFunctionCall_FunctionCall();

  /**
   * Returns the meta object for the containment reference list '{@link fr.ensma.dsl.threeAddressCode.FunctionCall#getFunctionArgument <em>Function Argument</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Function Argument</em>'.
   * @see fr.ensma.dsl.threeAddressCode.FunctionCall#getFunctionArgument()
   * @see #getFunctionCall()
   * @generated
   */
  EReference getFunctionCall_FunctionArgument();

  /**
   * Returns the meta object for class '{@link fr.ensma.dsl.threeAddressCode.FunctionParam <em>Function Param</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Function Param</em>'.
   * @see fr.ensma.dsl.threeAddressCode.FunctionParam
   * @generated
   */
  EClass getFunctionParam();

  /**
   * Returns the meta object for the containment reference list '{@link fr.ensma.dsl.threeAddressCode.FunctionParam#getStruct <em>Struct</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Struct</em>'.
   * @see fr.ensma.dsl.threeAddressCode.FunctionParam#getStruct()
   * @see #getFunctionParam()
   * @generated
   */
  EReference getFunctionParam_Struct();

  /**
   * Returns the meta object for the containment reference '{@link fr.ensma.dsl.threeAddressCode.FunctionParam#getDatatype <em>Datatype</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Datatype</em>'.
   * @see fr.ensma.dsl.threeAddressCode.FunctionParam#getDatatype()
   * @see #getFunctionParam()
   * @generated
   */
  EReference getFunctionParam_Datatype();

  /**
   * Returns the meta object for the attribute '{@link fr.ensma.dsl.threeAddressCode.FunctionParam#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see fr.ensma.dsl.threeAddressCode.FunctionParam#getName()
   * @see #getFunctionParam()
   * @generated
   */
  EAttribute getFunctionParam_Name();

  /**
   * Returns the meta object for class '{@link fr.ensma.dsl.threeAddressCode.FunctionArgument <em>Function Argument</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Function Argument</em>'.
   * @see fr.ensma.dsl.threeAddressCode.FunctionArgument
   * @generated
   */
  EClass getFunctionArgument();

  /**
   * Returns the meta object for class '{@link fr.ensma.dsl.threeAddressCode.DataType <em>Data Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Data Type</em>'.
   * @see fr.ensma.dsl.threeAddressCode.DataType
   * @generated
   */
  EClass getDataType();

  /**
   * Returns the meta object for class '{@link fr.ensma.dsl.threeAddressCode.Struct <em>Struct</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Struct</em>'.
   * @see fr.ensma.dsl.threeAddressCode.Struct
   * @generated
   */
  EClass getStruct();

  /**
   * Returns the meta object for class '{@link fr.ensma.dsl.threeAddressCode.Goto <em>Goto</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Goto</em>'.
   * @see fr.ensma.dsl.threeAddressCode.Goto
   * @generated
   */
  EClass getGoto();

  /**
   * Returns the meta object for class '{@link fr.ensma.dsl.threeAddressCode.Label <em>Label</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Label</em>'.
   * @see fr.ensma.dsl.threeAddressCode.Label
   * @generated
   */
  EClass getLabel();

  /**
   * Returns the meta object for class '{@link fr.ensma.dsl.threeAddressCode.If <em>If</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>If</em>'.
   * @see fr.ensma.dsl.threeAddressCode.If
   * @generated
   */
  EClass getIf();

  /**
   * Returns the meta object for class '{@link fr.ensma.dsl.threeAddressCode.AssignOperation <em>Assign Operation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Assign Operation</em>'.
   * @see fr.ensma.dsl.threeAddressCode.AssignOperation
   * @generated
   */
  EClass getAssignOperation();

  /**
   * Returns the meta object for the containment reference list '{@link fr.ensma.dsl.threeAddressCode.AssignOperation#getFunctionCall <em>Function Call</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Function Call</em>'.
   * @see fr.ensma.dsl.threeAddressCode.AssignOperation#getFunctionCall()
   * @see #getAssignOperation()
   * @generated
   */
  EReference getAssignOperation_FunctionCall();

  /**
   * Returns the meta object for class '{@link fr.ensma.dsl.threeAddressCode.Function <em>Function</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Function</em>'.
   * @see fr.ensma.dsl.threeAddressCode.Function
   * @generated
   */
  EClass getFunction();

  /**
   * Returns the meta object for the attribute '{@link fr.ensma.dsl.threeAddressCode.Function#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see fr.ensma.dsl.threeAddressCode.Function#getName()
   * @see #getFunction()
   * @generated
   */
  EAttribute getFunction_Name();

  /**
   * Returns the meta object for class '{@link fr.ensma.dsl.threeAddressCode.BouleanExrpession <em>Boulean Exrpession</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Boulean Exrpession</em>'.
   * @see fr.ensma.dsl.threeAddressCode.BouleanExrpession
   * @generated
   */
  EClass getBouleanExrpession();

  /**
   * Returns the meta object for class '{@link fr.ensma.dsl.threeAddressCode.ArithmeticOperation <em>Arithmetic Operation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Arithmetic Operation</em>'.
   * @see fr.ensma.dsl.threeAddressCode.ArithmeticOperation
   * @generated
   */
  EClass getArithmeticOperation();

  /**
   * Returns the meta object for class '{@link fr.ensma.dsl.threeAddressCode.LogicalOperation <em>Logical Operation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Logical Operation</em>'.
   * @see fr.ensma.dsl.threeAddressCode.LogicalOperation
   * @generated
   */
  EClass getLogicalOperation();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  ThreeAddressCodeFactory getThreeAddressCodeFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link fr.ensma.dsl.threeAddressCode.impl.TACImpl <em>TAC</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.ensma.dsl.threeAddressCode.impl.TACImpl
     * @see fr.ensma.dsl.threeAddressCode.impl.ThreeAddressCodePackageImpl#getTAC()
     * @generated
     */
    EClass TAC = eINSTANCE.getTAC();

    /**
     * The meta object literal for the '<em><b>Tac</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TAC__TAC = eINSTANCE.getTAC_Tac();

    /**
     * The meta object literal for the '{@link fr.ensma.dsl.threeAddressCode.impl.FunctionDefImpl <em>Function Def</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.ensma.dsl.threeAddressCode.impl.FunctionDefImpl
     * @see fr.ensma.dsl.threeAddressCode.impl.ThreeAddressCodePackageImpl#getFunctionDef()
     * @generated
     */
    EClass FUNCTION_DEF = eINSTANCE.getFunctionDef();

    /**
     * The meta object literal for the '<em><b>Function</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FUNCTION_DEF__FUNCTION = eINSTANCE.getFunctionDef_Function();

    /**
     * The meta object literal for the '<em><b>Functionparam</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FUNCTION_DEF__FUNCTIONPARAM = eINSTANCE.getFunctionDef_Functionparam();

    /**
     * The meta object literal for the '<em><b>Struct</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FUNCTION_DEF__STRUCT = eINSTANCE.getFunctionDef_Struct();

    /**
     * The meta object literal for the '<em><b>Label</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FUNCTION_DEF__LABEL = eINSTANCE.getFunctionDef_Label();

    /**
     * The meta object literal for the '<em><b>Goto</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FUNCTION_DEF__GOTO = eINSTANCE.getFunctionDef_Goto();

    /**
     * The meta object literal for the '<em><b>If</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FUNCTION_DEF__IF = eINSTANCE.getFunctionDef_If();

    /**
     * The meta object literal for the '<em><b>Function Call</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FUNCTION_DEF__FUNCTION_CALL = eINSTANCE.getFunctionDef_FunctionCall();

    /**
     * The meta object literal for the '<em><b>Assign Op</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FUNCTION_DEF__ASSIGN_OP = eINSTANCE.getFunctionDef_AssignOp();

    /**
     * The meta object literal for the '{@link fr.ensma.dsl.threeAddressCode.impl.FunctionCallImpl <em>Function Call</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.ensma.dsl.threeAddressCode.impl.FunctionCallImpl
     * @see fr.ensma.dsl.threeAddressCode.impl.ThreeAddressCodePackageImpl#getFunctionCall()
     * @generated
     */
    EClass FUNCTION_CALL = eINSTANCE.getFunctionCall();

    /**
     * The meta object literal for the '<em><b>Function Call</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FUNCTION_CALL__FUNCTION_CALL = eINSTANCE.getFunctionCall_FunctionCall();

    /**
     * The meta object literal for the '<em><b>Function Argument</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FUNCTION_CALL__FUNCTION_ARGUMENT = eINSTANCE.getFunctionCall_FunctionArgument();

    /**
     * The meta object literal for the '{@link fr.ensma.dsl.threeAddressCode.impl.FunctionParamImpl <em>Function Param</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.ensma.dsl.threeAddressCode.impl.FunctionParamImpl
     * @see fr.ensma.dsl.threeAddressCode.impl.ThreeAddressCodePackageImpl#getFunctionParam()
     * @generated
     */
    EClass FUNCTION_PARAM = eINSTANCE.getFunctionParam();

    /**
     * The meta object literal for the '<em><b>Struct</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FUNCTION_PARAM__STRUCT = eINSTANCE.getFunctionParam_Struct();

    /**
     * The meta object literal for the '<em><b>Datatype</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FUNCTION_PARAM__DATATYPE = eINSTANCE.getFunctionParam_Datatype();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FUNCTION_PARAM__NAME = eINSTANCE.getFunctionParam_Name();

    /**
     * The meta object literal for the '{@link fr.ensma.dsl.threeAddressCode.impl.FunctionArgumentImpl <em>Function Argument</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.ensma.dsl.threeAddressCode.impl.FunctionArgumentImpl
     * @see fr.ensma.dsl.threeAddressCode.impl.ThreeAddressCodePackageImpl#getFunctionArgument()
     * @generated
     */
    EClass FUNCTION_ARGUMENT = eINSTANCE.getFunctionArgument();

    /**
     * The meta object literal for the '{@link fr.ensma.dsl.threeAddressCode.impl.DataTypeImpl <em>Data Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.ensma.dsl.threeAddressCode.impl.DataTypeImpl
     * @see fr.ensma.dsl.threeAddressCode.impl.ThreeAddressCodePackageImpl#getDataType()
     * @generated
     */
    EClass DATA_TYPE = eINSTANCE.getDataType();

    /**
     * The meta object literal for the '{@link fr.ensma.dsl.threeAddressCode.impl.StructImpl <em>Struct</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.ensma.dsl.threeAddressCode.impl.StructImpl
     * @see fr.ensma.dsl.threeAddressCode.impl.ThreeAddressCodePackageImpl#getStruct()
     * @generated
     */
    EClass STRUCT = eINSTANCE.getStruct();

    /**
     * The meta object literal for the '{@link fr.ensma.dsl.threeAddressCode.impl.GotoImpl <em>Goto</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.ensma.dsl.threeAddressCode.impl.GotoImpl
     * @see fr.ensma.dsl.threeAddressCode.impl.ThreeAddressCodePackageImpl#getGoto()
     * @generated
     */
    EClass GOTO = eINSTANCE.getGoto();

    /**
     * The meta object literal for the '{@link fr.ensma.dsl.threeAddressCode.impl.LabelImpl <em>Label</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.ensma.dsl.threeAddressCode.impl.LabelImpl
     * @see fr.ensma.dsl.threeAddressCode.impl.ThreeAddressCodePackageImpl#getLabel()
     * @generated
     */
    EClass LABEL = eINSTANCE.getLabel();

    /**
     * The meta object literal for the '{@link fr.ensma.dsl.threeAddressCode.impl.IfImpl <em>If</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.ensma.dsl.threeAddressCode.impl.IfImpl
     * @see fr.ensma.dsl.threeAddressCode.impl.ThreeAddressCodePackageImpl#getIf()
     * @generated
     */
    EClass IF = eINSTANCE.getIf();

    /**
     * The meta object literal for the '{@link fr.ensma.dsl.threeAddressCode.impl.AssignOperationImpl <em>Assign Operation</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.ensma.dsl.threeAddressCode.impl.AssignOperationImpl
     * @see fr.ensma.dsl.threeAddressCode.impl.ThreeAddressCodePackageImpl#getAssignOperation()
     * @generated
     */
    EClass ASSIGN_OPERATION = eINSTANCE.getAssignOperation();

    /**
     * The meta object literal for the '<em><b>Function Call</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ASSIGN_OPERATION__FUNCTION_CALL = eINSTANCE.getAssignOperation_FunctionCall();

    /**
     * The meta object literal for the '{@link fr.ensma.dsl.threeAddressCode.impl.FunctionImpl <em>Function</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.ensma.dsl.threeAddressCode.impl.FunctionImpl
     * @see fr.ensma.dsl.threeAddressCode.impl.ThreeAddressCodePackageImpl#getFunction()
     * @generated
     */
    EClass FUNCTION = eINSTANCE.getFunction();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FUNCTION__NAME = eINSTANCE.getFunction_Name();

    /**
     * The meta object literal for the '{@link fr.ensma.dsl.threeAddressCode.impl.BouleanExrpessionImpl <em>Boulean Exrpession</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.ensma.dsl.threeAddressCode.impl.BouleanExrpessionImpl
     * @see fr.ensma.dsl.threeAddressCode.impl.ThreeAddressCodePackageImpl#getBouleanExrpession()
     * @generated
     */
    EClass BOULEAN_EXRPESSION = eINSTANCE.getBouleanExrpession();

    /**
     * The meta object literal for the '{@link fr.ensma.dsl.threeAddressCode.impl.ArithmeticOperationImpl <em>Arithmetic Operation</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.ensma.dsl.threeAddressCode.impl.ArithmeticOperationImpl
     * @see fr.ensma.dsl.threeAddressCode.impl.ThreeAddressCodePackageImpl#getArithmeticOperation()
     * @generated
     */
    EClass ARITHMETIC_OPERATION = eINSTANCE.getArithmeticOperation();

    /**
     * The meta object literal for the '{@link fr.ensma.dsl.threeAddressCode.impl.LogicalOperationImpl <em>Logical Operation</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.ensma.dsl.threeAddressCode.impl.LogicalOperationImpl
     * @see fr.ensma.dsl.threeAddressCode.impl.ThreeAddressCodePackageImpl#getLogicalOperation()
     * @generated
     */
    EClass LOGICAL_OPERATION = eINSTANCE.getLogicalOperation();

  }

} //ThreeAddressCodePackage
